/* Write your PL/SQL query statement below */
WITH CTE_1 AS (
SELECT 
DISTINCT PUR.USER_ID,INFO.CATEGORY
FROM PRODUCTPURCHASES PUR
INNER JOIN PRODUCTINFO INFO ON PUR.PRODUCT_ID=INFO.PRODUCT_ID
ORDER BY PUR.USER_ID),

CTE_2 AS (
SELECT C.USER_ID,C.CATEGORY AS CAT1,C1.CATEGORY AS CAT2
FROM CTE_1 C
INNER JOIN CTE_1 C1 ON C.USER_ID=C1.USER_ID
WHERE C.CATEGORY<C1.CATEGORY)

SELECT 
CAT1 "CATEGORY1",CAT2 "CATEGORY2",COUNT(USER_ID) "CUSTOMER_COUNT"
FROM CTE_2
GROUP BY CAT1,CAT2
HAVING COUNT(USER_ID)>2
ORDER BY COUNT(USER_ID) DESC,CAT1,CAT2